services:
  database:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin778
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    restart: unless-stopped
  app:
    restart: unless-stopped
    build: .
    ports:
      - "8189:8189"
    depends_on:
      - database
    environment:
      DB_URL: 'jdbc:postgresql://db:5432/example_db'
      DB_USER: postgres
      DB_PASSWORD: admin778

volumes:
  pg_db:
